apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: leaderboard-howto
build:
  artifacts:
  - image: leaderboards-demo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: leaderboards-demo
  port: 8080
