apiVersion: skaffold/v2beta22
kind: Confighelnm
metadata:
  name: leaderboard-howto
build:
  artifacts:
  - image: leaderboards-demo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./kube-manifests/deployment.yaml
    - ./kube-manifests/redis.yaml
portForward:
- resourceType: service
  resourceName: leaderboards-demo
  port: 8080
